/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as WatchContentIdRouteImport } from './routes/watch.$contentId'
import { Route as AdminTvRouteImport } from './routes/admin/tv'
import { Route as AdminMoviesRouteImport } from './routes/admin/movies'
import { Route as AdminTmdbTrendingRouteImport } from './routes/admin/tmdb/trending'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const WatchContentIdRoute = WatchContentIdRouteImport.update({
  id: '/watch/$contentId',
  path: '/watch/$contentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTvRoute = AdminTvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMoviesRoute = AdminMoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTmdbTrendingRoute = AdminTmdbTrendingRouteImport.update({
  id: '/tmdb/trending',
  path: '/tmdb/trending',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/movies': typeof AdminMoviesRoute
  '/admin/tv': typeof AdminTvRoute
  '/watch/$contentId': typeof WatchContentIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/tmdb/trending': typeof AdminTmdbTrendingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/movies': typeof AdminMoviesRoute
  '/admin/tv': typeof AdminTvRoute
  '/watch/$contentId': typeof WatchContentIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/tmdb/trending': typeof AdminTmdbTrendingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/movies': typeof AdminMoviesRoute
  '/admin/tv': typeof AdminTvRoute
  '/watch/$contentId': typeof WatchContentIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/tmdb/trending': typeof AdminTmdbTrendingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/movies'
    | '/admin/tv'
    | '/watch/$contentId'
    | '/admin/'
    | '/admin/tmdb/trending'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/movies'
    | '/admin/tv'
    | '/watch/$contentId'
    | '/admin'
    | '/admin/tmdb/trending'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/movies'
    | '/admin/tv'
    | '/watch/$contentId'
    | '/admin/'
    | '/admin/tmdb/trending'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  WatchContentIdRoute: typeof WatchContentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/watch/$contentId': {
      id: '/watch/$contentId'
      path: '/watch/$contentId'
      fullPath: '/watch/$contentId'
      preLoaderRoute: typeof WatchContentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tv': {
      id: '/admin/tv'
      path: '/tv'
      fullPath: '/admin/tv'
      preLoaderRoute: typeof AdminTvRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/movies': {
      id: '/admin/movies'
      path: '/movies'
      fullPath: '/admin/movies'
      preLoaderRoute: typeof AdminMoviesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tmdb/trending': {
      id: '/admin/tmdb/trending'
      path: '/tmdb/trending'
      fullPath: '/admin/tmdb/trending'
      preLoaderRoute: typeof AdminTmdbTrendingRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminMoviesRoute: typeof AdminMoviesRoute
  AdminTvRoute: typeof AdminTvRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminTmdbTrendingRoute: typeof AdminTmdbTrendingRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminMoviesRoute: AdminMoviesRoute,
  AdminTvRoute: AdminTvRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminTmdbTrendingRoute: AdminTmdbTrendingRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  WatchContentIdRoute: WatchContentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
